services:
  database:
    image: postgres:16
    command: ["postgres", "-c", "listen_addresses=*"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -p 5432 -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ULRS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: "1"
    volumes:
      - ./backend:/src
    depends_on:
      database:
        condition: service_healthy
    command: ["dotnet", "watch", "run"]

volumes:
  pgdata:
